//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyMedia.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilePicture
    {
        public int Id { get; set; }
        public int UId { get; set; }
        public string ImagePath { get; set; }
    
        public virtual User User { get; set; }
    }
}
